### ISSUE TITLE
QUESTION: Instructions for adding Remarkable plugins to gulp-remarkable?

### ISSUE THREAD

**Issue by caraya** [johno/gulp-remarkable#14]
How do you add plugins to gulp-remarkable workflow? I've seen the instructions in Remarkable's Readme but can't find an equivalent for gulp-remarkable. Is there a way to do it?

**Comment by Charon77** [comment]
#15 solves this. Pass a function(md) to the 2nd parameter, and push the plugin to the md object.

**Comment by caraya** [comment]
Do you have an actual example that illustrates how to do it? Waiting for the PR to get accepted (or closed if it has been  already merged)

**Comment by Charon77** [comment]
@caraya 
Hello. As in #15, here's a further explanation to the code

```js
return gulp.src(globMarkdown)
    .pipe(markdown(opts, (md=>{
      md.renderer.rules.heading_open = headingAnchorRendererPlugin
    })))

function headingAnchorRendererPlugin(tokens, idx ) {
  if (tokens[idx+1].type == 'inline') {
    let heading_anchor = slug(tokens[idx+1].content, {lower: true})
    return '<h' + tokens[idx].hLevel + ' id="' + heading_anchor + '">';
  }
  return '<h' + tokens[idx].hLevel + '>';
}
```

The current state of gulp-markdown only allows you to do so:

`.pipe(markdown(options))`

what #15 does is adding an optional function argument to the markdown function:

`.pipe(markdown(options, fn))`

If defined, `fn` is expected to be a function with one argument: the markdown object.

Inside the function, you can do modifications to the markdown object, including
adding plugins.

`fn` could either look like this:

```js
function fn(md) {
  md.renderer.rules.heading_open = headingAnchorRendererPlugin
}
```
Or as in the example the second argument is

```js
(md=>{
    md.renderer.rules.heading_open = headingAnchorRendererPlugin
  })
```
which is the ES6 syntax for lambda function to replace the heading_open rendering rule.
headingAnchorRendererPlugin is the plugin function, described [here][renderer].

While waiting for @johnotander to review the PR, you can use _temporarily_ the code from my
repo by
`npm remove gulp-remarkable`
`npm install charon77/gulp-remarkable`

Cheers 🍺 

[renderer]: https://github.com/jonschlinkert/remarkable/blob/master/docs/renderer.md

**Comment by caraya** [comment]
Sorry to be obtuse but this doesn't really answer the question. This assumes I'm writing my own plugin and not using a pre-existing one. I don't know enough about the internals of Remarkable to know if this is the same process everywhere or if existing plugins, like video or others, work the same way. 

I may consider using something like this but would rather leverage the existing plugin ecosystem

**Comment by Charon77** [comment]
@caraya This can also be used for using pre-existing plugins.

For example, suppose I'm using pretty-remarkable by jonschlinkert
[pretty-remarkable](https://github.com/jonschlinkert/pretty-remarkable)

Here's how you can do it if this get merged:

```js
const prettify = require('pretty-remarkable') //The plugin we want to include
const md = require('gulp-remarkable')

gulp.task('remarkable' function() {
  return gulp.src('./*.md')
    .pipe(md(opts, function(md){ 
        md.use(prettify)                                        //Here we're using the plugin from pretty-remarkable
    }))
})
```

Inside the function, we can call functions such as `use`, to load the plugin.
Of course, this works for every other plugins written for remarkable.

Hope this clears the confusion.
Cheers 🍺
